Attempt to fix Jenkinsfile for digitiser capture
groovy.lang.MissingPropertyException: No such property: katsdp for
class: WorkflowScript

I'm guessing that the function doesn't have visibility of the "global"
variable.